//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Money_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public account()
        {
            this.account_money = new HashSet<account_money>();
            this.trans = new HashSet<tran>();
        }
    
        public int acc_id { get; set; }
        public string acc_email { get; set; }
        public string acc_username { get; set; }
        public string acc_password { get; set; }
        public Nullable<System.DateTime> acc_create_time { get; set; }
        public Nullable<decimal> acc_balance { get; set; }
        public Nullable<bool> acc_verified { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<account_money> account_money { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<tran> trans { get; set; }
    }
}
