//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Money_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class account_money
    {
        public int acc_id { get; set; }
        public int bm_id { get; set; }
        public Nullable<int> quantity { get; set; }
    
        public virtual account account { get; set; }
        public virtual base_money base_money { get; set; }
    }
}
