//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Money_Management.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class money_managementEntities : DbContext
    {
        public money_managementEntities()
            : base("name=money_managementEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<account> accounts { get; set; }
        public virtual DbSet<account_money> account_money { get; set; }
        public virtual DbSet<base_money> base_money { get; set; }
        public virtual DbSet<category> categories { get; set; }
        public virtual DbSet<tran> trans { get; set; }
        public virtual DbSet<trans_type> trans_type { get; set; }
        public virtual DbSet<trans_detail> trans_detail { get; set; }
    
        public virtual int P_UpdateQuantityAfterTrans()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("P_UpdateQuantityAfterTrans");
        }
    }
}
