//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Money_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trans_detail
    {
        public int t_id { get; set; }
        public int bm_id { get; set; }
        public Nullable<int> t_quantity { get; set; }
    
        public virtual base_money base_money { get; set; }
        public virtual tran tran { get; set; }
    }
}
