//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Money_Management.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tran
    {
        public int t_id { get; set; }
        public Nullable<System.DateTime> t_date { get; set; }
        public string t_info { get; set; }
        public Nullable<int> type_id { get; set; }
        public Nullable<int> c_id { get; set; }
        public Nullable<int> acc_id { get; set; }
    
        public virtual account account { get; set; }
        public virtual category category { get; set; }
        public virtual trans_detail trans_detail { get; set; }
        public virtual trans_type trans_type { get; set; }
    }
}
